import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'test', 'production')
    .default('development'),
  PORT: Joi.number().port().default(3000),
  API_PREFIX: Joi.string().default('api'),
  DATABASE_PATH: Joi.string().trim().min(1).required(),
  FACTURACION: Joi.boolean().truthy('true').falsy('false').default(false),
  MENSUALIDADES: Joi.boolean().truthy('true').falsy('false').default(false),
  TYPEORM_LOGGING: Joi.boolean().truthy('true').falsy('false').default(false),
  SERVER_LINK_URL: Joi.string().uri().default('http://localhost:3001'),
  SERVER_LINK_NAMESPACE: Joi.string().default('/'),
  PPE_DEVICE_UUID: Joi.string().allow('').default(''),
  PPE_DEVICE_SECRET: Joi.string().allow('').default(''),
  NEXO_BACK_KEY_CRYPTO: Joi.string().allow('').default(''),
  LOCAL_API_ADMIN_KEY: Joi.string().allow('').default(''),
  LOCAL_API_OPERATOR_KEY: Joi.string().allow('').default(''),
  LOCAL_API_AUDIT_KEY: Joi.string().allow('').default(''),
  PPE_JWT_SECRET: Joi.string().min(32).default('CHANGE-THIS-PPE-JWT-SECRET-FOR-PROD-USE'),
  PPE_JWT_EXPIRES_IN: Joi.string().default('4h'),
  PRINTER_JAVA_SERVER_URL: Joi.string().uri().default('http://localhost:8080/imprimir'),
  PRINTER_NAME: Joi.string().default('printer'),
  // Espacios a la izquierda de las lineas alineadas a la izquierda (margen del ticket)
  PRINTER_LEFT_PADDING: Joi.number().integer().min(0).max(10).default(1),
  PPE_MACHINE_NAME: Joi.string().default('PPE'),
  PAYMENT_SESSION_VALIDATING_TIMEOUT_MS: Joi.number().integer().min(5_000).default(15_000),
  PAYMENT_SESSION_REVIEW_TIMEOUT_MS: Joi.number().integer().min(5_000).default(30_000),
  PAYMENT_SESSION_CASH_TIMEOUT_MS: Joi.number().integer().min(30_000).default(30_000),
  PAYMENT_SESSION_BILLING_DETAILS_TIMEOUT_MS: Joi.number().integer().min(30_000).default(300_000),
  PAYMENT_SESSION_MONTHLY_SUBSCRIPTION_TIMEOUT_MS: Joi.number().integer().min(30_000).default(120_000),
  PAYMENT_SESSION_FINALIZING_TIMEOUT_MS: Joi.number().integer().min(5_000).default(30_000),
  SIMULATE_HARDWARE: Joi.boolean().truthy('true').falsy('false').default(false),
  BILL_VALIDATOR_LEGACY_PATH: Joi.string().allow('').default(''),
  ELECTRONIC_BOARD_LEGACY_PATH: Joi.string().allow('').default(''),
  QR_SCANNER_PORT: Joi.string().allow('').default(''),
  QR_SCANNER_BAUD_RATE: Joi.number().integer().min(1200).default(115200),
  QR_SCANNER_DUPLICATE_COOLDOWN_MS: Joi.number().integer().min(0).default(4_000),
  BILL_VALIDATOR_PORT: Joi.string().allow('').default(''),
  ELECTRONIC_BOARD_PORT: Joi.string().allow('').default(''),
  ELECTRONIC_BOARD_USB_VID: Joi.string().allow('').default(''),
  ELECTRONIC_BOARD_USB_PID: Joi.string().allow('').default(''),
  QR_SCANNER_USB_VID: Joi.string().allow('').default(''),
  QR_SCANNER_USB_PID: Joi.string().allow('').default(''),
  BILL_VALIDATOR_USB_VID: Joi.string().allow('').default(''),
  BILL_VALIDATOR_USB_PID: Joi.string().allow('').default(''),
});
